### ISSUE TITLE
Unable to install (Xcode 15, beta 7), iOS17 (simulator)

### ISSUE THREAD

**Issue by staticdreams** [WilhelmOks/ModifiedCopyMacro#2]
The package itself installs, but wont compile afterwards, throwing 2 errors inside `ModifiedCopyMacro.swift` on:

     line 44:  
     let diagnostic = Diagnostic(node: .init(node), message: ModifiedCopyDiagnostic.notAStruct)
     // Type 'SyntaxProtocol' cannot be instantiated
     
     line 69: 
     private static func accessorIsAllowed(_ accessor: PatternBindingSyntax.Accessor?) -> Bool {
     // 'Accessor' is not a member type of struct 'SwiftSyntax.PatternBindingSyntax'

**Comment by WilhelmOks** [comment]
It looks like some of the api has changed with beta 7. I'll have a look at it.

**Comment by WilhelmOks** [comment]
I just downloaded and installed Xcode 15 beta 7 and it works for me. No compilation errors. Tests are passing and an example project with that package as a dependency works.

Not sure why you get the error but maybe you can clean build or something.
